/*
 * 本文件属于 红月创作 (Hongyue Creation) 项目。
 * Copyright (C) 2026 chen647208
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * 本程序为自由软件：您可依据 GNU Affero 通用公共许可证第 3 版（AGPL-3.0-only）修改与分发；
 * 商业闭源使用需另行获取授权，详见 docs/guides/licensing.md。
 */

import type { TypeTemplate } from './registry';

/**
 * 内置类型模板首批（docs/design/03 §2 表）。
 * 字段清单从现有 shared/types.ts 领域类型直接转写（保证投影无损），
 * 并对齐 Manuskript 实测字段（角色弧线四件套 motivation/goal/conflict/epiphany 等）。
 * ref 字段声明 refType —— 投影层据此把值存为 relation 属性（可被索引反查）。
 */

const NOVEL_TEMPLATES: TypeTemplate[] = [
  {
    id: 'novel.book',
    label: '书',
    labelEn: 'Book',
    icon: 'book',
    category: 'novel',
    fields: [
      { key: 'inspiration', label: '灵感', labelEn: 'Inspiration', type: 'richtext' },
      { key: 'intro', label: '简介', labelEn: 'Intro', type: 'richtext' },
      { key: 'synopsis', label: '梗概', labelEn: 'Synopsis', type: 'richtext' },
    ],
    views: ['outline'],
    dslHint: { headingLevel: 1 },
  },
  {
    id: 'novel.part',
    label: '幕/部',
    labelEn: 'Part',
    icon: 'layers',
    category: 'novel',
    fields: [
      { key: 'synopsis', label: '梗概', type: 'richtext' },
      { key: 'wordGoal', label: '字数目标', type: 'number' },
      { key: 'compile', label: '参与编译', type: 'enum', enum: ['yes', 'no'] },
    ],
    views: ['outline', 'corkboard'],
    dslHint: { headingLevel: 1 },
  },
  {
    id: 'novel.chapter',
    label: '章节',
    labelEn: 'Chapter',
    icon: 'file-text',
    category: 'novel',
    fields: [
      { key: 'summary', label: '细纲', type: 'richtext' },
      { key: 'contentSummary', label: '正文摘要', type: 'richtext' },
      { key: 'order', label: '序号', type: 'number' },
      { key: 'pov', label: '视角人物', type: 'ref', refType: 'card.character' },
      { key: 'status', label: '状态', type: 'enum', enum: ['draft', 'outline', 'done'] },
      { key: 'labels', label: '标签', type: 'list' },
      { key: 'wordGoal', label: '字数目标', type: 'number' },
      { key: 'setGoal', label: '场景地点', type: 'ref', refType: 'card.location' },
      { key: 'compile', label: '参与编译', type: 'enum', enum: ['yes', 'no'] },
      { key: 'mainLocationId', label: '主要地点', type: 'ref', refType: 'card.location' },
      { key: 'involvedFactionIds', label: '涉及势力', type: 'list' },
      { key: 'timelineEventId', label: '时间线事件', type: 'ref', refType: 'meta.timeline-event' },
      { key: 'storyDate', label: '故事内时间', type: 'json' },
      { key: 'history', label: 'AI 生成历史', type: 'json' },
      { key: 'snapshots', label: '编辑快照', type: 'json' },
    ],
    views: ['outline', 'corkboard', 'table'],
    statusLabels: 'status',
    dslHint: { headingLevel: 2 },
  },
  {
    id: 'novel.scene',
    label: '场景',
    labelEn: 'Scene',
    icon: 'clapperboard',
    category: 'novel',
    fields: [
      { key: 'pov', label: '视角人物', type: 'ref', refType: 'card.character' },
      { key: 'status', label: '状态', type: 'enum', enum: ['draft', 'outline', 'done'] },
      { key: 'labels', label: '标签', type: 'list' },
      { key: 'synopsis', label: '梗概', type: 'richtext' },
      { key: 'wordGoal', label: '字数目标', type: 'number' },
      { key: 'strand', label: '叙事线', type: 'ref', refType: 'meta.strand' },
    ],
    views: ['corkboard', 'table'],
    statusLabels: 'status',
    dslHint: { headingLevel: 3 },
  },
];

const CARD_TEMPLATES: TypeTemplate[] = [
  {
    id: 'card.character',
    label: '人物',
    labelEn: 'Character',
    icon: 'user',
    category: 'card',
    tagKind: 'character',
    fields: [
      { key: 'gender', label: '性别', type: 'text' },
      { key: 'age', label: '年龄', type: 'text' },
      { key: 'role', label: '角色定位', type: 'text' },
      { key: 'importance', label: '重要度', type: 'enum', enum: ['main', 'supporting', 'minor'] },
      { key: 'alias', label: '别名', type: 'list' },
      { key: 'personality', label: '性格', type: 'richtext', group: '内在' },
      { key: 'background', label: '背景', type: 'richtext', group: '内在' },
      { key: 'motivation', label: '动机', type: 'richtext', group: '弧线' },
      { key: 'goal', label: '目标', type: 'richtext', group: '弧线' },
      { key: 'conflict', label: '冲突', type: 'richtext', group: '弧线' },
      { key: 'epiphany', label: '顿悟/转变', type: 'richtext', group: '弧线' },
      { key: 'characterArc', label: '成长弧线', type: 'richtext', group: '弧线' },
      { key: 'strengths', label: '优势', type: 'richtext', group: '评价' },
      { key: 'weaknesses', label: '弱点', type: 'richtext', group: '评价' },
      { key: 'appearance', label: '外貌', type: 'richtext', group: '外观' },
      { key: 'distinctiveFeatures', label: '标志性特征', type: 'richtext', group: '外观' },
      { key: 'occupation', label: '职业/身份', type: 'text', group: '外观' },
      { key: 'relationships', label: '关系', type: 'richtext', group: '关联' },
      { key: 'factionId', label: '所属势力', type: 'ref', refType: 'card.faction', group: '关联' },
      { key: 'homeLocationId', label: '出身地', type: 'ref', refType: 'card.location', group: '关联' },
      { key: 'currentLocationId', label: '当前所在地', type: 'ref', refType: 'card.location', group: '关联' },
      { key: 'ruleSystemLevel', label: '等级体系位置', type: 'json', group: '关联' },
      { key: 'birthInfo', label: '出生信息', type: 'json', group: '关联' },
      { key: 'birthDate', label: '出生日期', type: 'json', group: '关联' },
      { key: 'summary', label: '一句话简介', type: 'richtext' },
    ],
    views: ['sheet', 'table', 'graph'],
    statusLabels: 'importance',
  },
  {
    id: 'card.location',
    label: '地点',
    labelEn: 'Location',
    icon: 'map-pin',
    category: 'card',
    tagKind: 'location',
    fields: [
      { key: 'type', label: '类型', type: 'enum', enum: ['city', 'region', 'building', 'landmark', 'dungeon', 'wilderness', 'other'] },
      { key: 'description', label: '描述', type: 'richtext' },
      { key: 'passion', label: '魅力/热爱点', type: 'richtext', group: '氛围' },
      { key: 'conflict', label: '冲突点', type: 'richtext', group: '氛围' },
      { key: 'geography', label: '地理属性', type: 'json', group: '地理' },
      { key: 'region', label: '区域', type: 'text', group: '地理' },
      { key: 'tags', label: '特征标签', type: 'list' },
      { key: 'controlledBy', label: '控制势力', type: 'ref', refType: 'card.faction', group: '关联' },
      { key: 'connectedLocations', label: '关联地点', type: 'json', group: '关联' },
      { key: 'mapPosition', label: '地图位置', type: 'json', group: '关联' },
    ],
    views: ['sheet', 'table', 'graph'],
  },
  {
    id: 'card.faction',
    label: '势力',
    labelEn: 'Faction',
    icon: 'flag',
    category: 'card',
    tagKind: 'entity',
    fields: [
      { key: 'type', label: '类型', type: 'enum', enum: ['kingdom', 'empire', 'sect', 'guild', 'family', 'tribe', 'organization', 'alliance', 'other'] },
      { key: 'description', label: '描述', type: 'richtext' },
      { key: 'ideology', label: '理念/信仰', type: 'richtext', group: '内在' },
      { key: 'strength', label: '实力评估', type: 'json', group: '实力' },
      { key: 'emblem', label: '标志', type: 'text', group: '实力' },
      { key: 'relations', label: '势力关系', type: 'json', group: '关联' },
      { key: 'controlledLocationIds', label: '控制地点', type: 'list', group: '关联' },
      { key: 'memberCharacterIds', label: '成员', type: 'list', group: '关联' },
      { key: 'leaderId', label: '领袖', type: 'ref', refType: 'card.character', group: '关联' },
      { key: 'headquartersLocationId', label: '总部', type: 'ref', refType: 'card.location', group: '关联' },
      { key: 'territoryLocationIds', label: '领地', type: 'list', group: '关联' },
      { key: 'foundedDate', label: '创立时间', type: 'text', group: '关联' },
    ],
    views: ['sheet', 'table', 'graph'],
  },
  {
    id: 'card.item',
    label: '道具',
    labelEn: 'Item',
    icon: 'sword',
    category: 'card',
    tagKind: 'object',
    fields: [
      { key: 'description', label: '描述', type: 'richtext' },
      { key: 'holder', label: '当前持有', type: 'ref', refType: 'card.character' },
      { key: 'transitions', label: '易手记录', type: 'json' },
      { key: 'tags', label: '标签', type: 'list' },
    ],
    views: ['sheet', 'table'],
  },
  {
    id: 'card.entity',
    label: '通用实体',
    labelEn: 'Entity',
    icon: 'shapes',
    category: 'card',
    tagKind: 'entity',
    fields: [
      { key: 'description', label: '描述', type: 'richtext' },
      { key: 'tags', label: '标签', type: 'list' },
    ],
    views: ['sheet', 'table'],
  },
];

const WORLD_TEMPLATES: TypeTemplate[] = [
  {
    id: 'world.magic-system',
    label: '魔法体系',
    labelEn: 'Magic System',
    icon: 'sparkles',
    category: 'meta',
    fields: [
      { key: 'description', label: '体系概述', type: 'richtext' },
      { key: 'rules', label: '规则', type: 'list' },
      { key: 'levels', label: '等级划分', type: 'json' },
      { key: 'limitations', label: '限制条件', type: 'richtext' },
      { key: 'castingMethod', label: '施法方式', type: 'text' },
    ],
    views: ['sheet'],
  },
  {
    id: 'world.tech-level',
    label: '科技水平',
    labelEn: 'Technology Level',
    icon: 'cpu',
    category: 'meta',
    fields: [
      { key: 'era', label: '时代', type: 'text' },
      { key: 'description', label: '描述', type: 'richtext' },
      { key: 'keyTechnologies', label: '关键技术', type: 'list' },
      { key: 'limitations', label: '技术限制', type: 'richtext' },
      { key: 'energySource', label: '能源类型', type: 'text' },
      { key: 'transportation', label: '交通方式', type: 'text' },
      { key: 'communication', label: '通讯方式', type: 'text' },
    ],
    views: ['sheet'],
  },
  {
    id: 'world.history',
    label: '历史背景',
    labelEn: 'World History',
    icon: 'scroll',
    category: 'meta',
    fields: [
      { key: 'overview', label: '历史概述', type: 'richtext' },
      { key: 'calendarSystem', label: '历法系统', type: 'text' },
      { key: 'keyEvents', label: '关键事件', type: 'json' },
    ],
    views: ['sheet', 'table'],
  },
  {
    id: 'world.rule-system',
    label: '规则系统',
    labelEn: 'Rule System',
    icon: 'list-ordered',
    category: 'meta',
    fields: [
      { key: 'type', label: '规则类型', type: 'enum', enum: ['cultivation', 'magic', 'tech', 'currency', 'organization', 'profession', 'title', 'custom'] },
      { key: 'description', label: '描述', type: 'richtext' },
      { key: 'levels', label: '等级定义', type: 'json' },
      { key: 'appliedToCharacterIds', label: '适用角色', type: 'list' },
    ],
    views: ['sheet', 'table'],
  },
];

const META_TEMPLATES: TypeTemplate[] = [
  {
    id: 'meta.timeline',
    label: '时间线',
    labelEn: 'Timeline',
    icon: 'git-commit-horizontal',
    category: 'meta',
    fields: [
      { key: 'name', label: '时间线名称', type: 'text' },
      { key: 'calendarSystem', label: '历法系统', type: 'text' },
      { key: 'startYear', label: '起始年份', type: 'number' },
    ],
    views: ['table', 'graph'],
  },
  {
    id: 'meta.timeline-event',
    label: '时间线事件',
    labelEn: 'Timeline Event',
    icon: 'calendar-clock',
    category: 'meta',
    tagKind: 'custom',
    fields: [
      { key: 'date', label: '日期', type: 'json' },
      { key: 'type', label: '事件类型', type: 'enum', enum: ['plot', 'character', 'world', 'faction', 'battle', 'discovery', 'other'] },
      { key: 'description', label: '描述', type: 'richtext' },
      { key: 'impact', label: '影响', type: 'richtext' },
      { key: 'relatedCharacterIds', label: '关联角色', type: 'list' },
      { key: 'relatedLocationIds', label: '关联地点', type: 'list' },
      { key: 'relatedFactionIds', label: '关联势力', type: 'list' },
      { key: 'relatedChapterId', label: '关联章节', type: 'ref', refType: 'novel.chapter' },
      { key: 'order', label: '顺序', type: 'number' },
    ],
    views: ['table', 'graph'],
  },
  {
    id: 'meta.foreshadow',
    label: '伏笔',
    labelEn: 'Foreshadow',
    icon: 'link',
    category: 'meta',
    fields: [
      { key: 'detail', label: '具体内容与预期回收方式', type: 'richtext' },
      { key: 'status', label: '状态', type: 'enum', enum: ['planted', 'paid-off', 'abandoned'] },
      { key: 'importance', label: '重要度', type: 'enum', enum: ['minor', 'major', 'critical'] },
      { key: 'plantedChapterId', label: '埋设章节', type: 'ref', refType: 'novel.chapter' },
      { key: 'plantedChapterOrder', label: '埋设序号', type: 'number' },
      { key: 'payoffChapterId', label: '回收章节', type: 'ref', refType: 'novel.chapter' },
      { key: 'payoffChapterOrder', label: '回收序号', type: 'number' },
      { key: 'tags', label: '标签', type: 'list' },
      { key: 'notes', label: '备注', type: 'richtext' },
    ],
    views: ['table'],
    statusLabels: 'status',
  },
  {
    id: 'meta.strand',
    label: '叙事线',
    labelEn: 'Strand',
    icon: 'git-branch',
    category: 'meta',
    fields: [
      { key: 'color', label: '颜色', type: 'text' },
      { key: 'description', label: '描述', type: 'richtext' },
    ],
    views: ['table', 'graph'],
  },
  {
    id: 'meta.knowledge',
    label: '知识库条目',
    labelEn: 'Knowledge',
    icon: 'library',
    category: 'meta',
    fields: [
      { key: 'category', label: '分类', type: 'enum', enum: ['inspiration', 'character', 'outline', 'chapter', 'writing'] },
      { key: 'type', label: '类型', type: 'text' },
      { key: 'size', label: '大小', type: 'number' },
      { key: 'addedAt', label: '添加时间', type: 'number' },
    ],
    views: ['table'],
  },
  {
    id: 'meta.prompt-card',
    label: '提示词卡',
    labelEn: 'Prompt Card',
    icon: 'terminal',
    category: 'meta',
    fields: [
      { key: 'category', label: '分类', type: 'text' },
      { key: 'nameKey', label: '内置名键', type: 'text' },
      { key: 'variables', label: '变量', type: 'list' },
      { key: 'requiredFields', label: '必填字段', type: 'list' },
      { key: 'fieldDescriptions', label: '字段说明', type: 'json' },
      { key: 'isDefault', label: '系统默认', type: 'boolean' },
      { key: 'previewExample', label: '预览示例', type: 'richtext' },
    ],
    views: ['table'],
  },
];

const SCRIPT_TEMPLATES: TypeTemplate[] = [
  {
    id: 'script.screenplay',
    label: '剧本',
    labelEn: 'Screenplay',
    icon: 'clapperboard',
    category: 'novel',
    fields: [
      { key: 'logline', label: '一句话梗概', type: 'text' },
      { key: 'genre', label: '类型', type: 'text' },
      { key: 'draftDate', label: '稿次/日期', type: 'text' },
      { key: 'status', label: '状态', type: 'enum', enum: ['draft', 'done'] },
    ],
    views: ['outline', 'table'],
    statusLabels: 'status',
  },
  {
    id: 'script.scene',
    label: '场次',
    labelEn: 'Scene',
    icon: 'clapperboard',
    category: 'novel',
    fields: [
      { key: 'sceneNumber', label: '场次号', type: 'number' },
      { key: 'location', label: '地点', type: 'ref', refType: 'card.location' },
      { key: 'timeOfDay', label: '时间', type: 'enum', enum: ['day', 'night', 'dawn', 'dusk'] },
      { key: 'cast', label: '出场角色', type: 'list' },
      { key: 'synopsis', label: '场次梗概', type: 'richtext' },
      { key: 'status', label: '状态', type: 'enum', enum: ['draft', 'done'] },
    ],
    views: ['corkboard', 'table'],
    statusLabels: 'status',
    dslHint: { headingLevel: 3 },
  },
  {
    id: 'storyboard.shot',
    label: '分镜',
    labelEn: 'Shot',
    icon: 'film',
    category: 'card',
    fields: [
      { key: 'shotNumber', label: '镜号', type: 'number' },
      { key: 'framing', label: '景别', type: 'enum', enum: ['wide', 'full', 'medium', 'close', 'extreme-close'] },
      { key: 'cameraMove', label: '镜头运动', type: 'text' },
      { key: 'duration', label: '时长（秒）', type: 'number' },
      { key: 'image', label: '画面', type: 'image' },
      { key: 'description', label: '画面描述', type: 'richtext' },
      { key: 'scene', label: '所属场次', type: 'ref', refType: 'script.scene' },
    ],
    views: ['corkboard', 'table'],
  },
  {
    id: 'bible.entry',
    label: '设定条目',
    labelEn: 'Series entry',
    icon: 'book-open',
    category: 'card',
    fields: [
      { key: 'category', label: '分类', type: 'text' },
      { key: 'summary', label: '摘要', type: 'text' },
      { key: 'details', label: '详情', type: 'richtext' },
      { key: 'tags', label: '标签', type: 'list' },
    ],
    views: ['table', 'corkboard'],
  },
  {
    id: 'comic.panel',
    label: '分格',
    labelEn: 'Panel',
    icon: 'layout-grid',
    category: 'novel',
    fields: [
      { key: 'panelNumber', label: '分格号', type: 'number' },
      { key: 'shot', label: '景别', type: 'text' },
      { key: 'image', label: '画面', type: 'image' },
      { key: 'dialogue', label: '对白', type: 'richtext' },
      { key: 'narration', label: '旁白', type: 'richtext' },
      { key: 'status', label: '状态', type: 'enum', enum: ['draft', 'done'] },
    ],
    views: ['corkboard', 'table'],
    statusLabels: 'status',
  },
];

export const BUILTIN_TEMPLATES: readonly TypeTemplate[] = [
  ...NOVEL_TEMPLATES,
  ...CARD_TEMPLATES,
  ...WORLD_TEMPLATES,
  ...META_TEMPLATES,
  ...SCRIPT_TEMPLATES,
];
